create table public.groups (
  id smallint generated by default as identity not null,
  name text not null,
  days_of_week smallint[] not null default '{}'::smallint[],
  spreadsheet_id text null,
  disabled_reminders reminders[] not null default '{}'::reminders[],
  acronym text not null,
  constraint groups_pkey primary key (id),
  constraint groups_name_key unique (name),
  constraint groups_spreadsheet_id_key unique (spreadsheet_id),
  constraint groups_days_of_week_check check (
    (
      days_of_week <@ array[
        (1)::smallint,
        (2)::smallint,
        (3)::smallint,
        (4)::smallint,
        (5)::smallint,
        (6)::smallint,
        (7)::smallint
      ]
    )
  )
) TABLESPACE pg_default;
